version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: projetweb
      MYSQL_USER: nndng
      MYSQL_PASSWORD: Nguyen2016
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3305:3306"
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: .
    command: flask run --host=0.0.0.0
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development
      DATABASE_URL: mysql+pymysql://nndng:Nguyen2016@db:3306/projetweb
      SECRET_KEY: your-very-secret-key
    depends_on:
      - db

volumes:
  db_data:
